### ISSUE TITLE
Doesn't generate unique strings in a Mongoose schema

### ISSUE THREAD

**Issue by shanev** [dylang/shortid#1]
I'm using shortid to generate a unique id for a Mongoose schema, like so:

```

Photo = new mongoose.Schema({
  _id: {
    type: String,
    default: shortId.generate()
  }
});
```

However, when subsequent Photos are created, the generated id is always the same. Not sure if this a Mongoose issue or shortid issue.

**Comment by danilodeveloper** [comment]
it worked for me:
```javascript
    publicId: {
        type: String,
        unique: true,
        'default': shortid.generate
    }
```
