### ISSUE TITLE
Depends on Array.prototype.filter (incompatible with PrototypeJS)

### ISSUE THREAD

**Issue by tylerbrandt** [dylang/shortid#103]
I noticed an incompatibility with this package and PrototypeJS < 1.7, due to it's use of `Array.prototype.filter` which clashes with the one that Prototype defines. Here's a reproducible test case to demonstrate: https://github.com/optimizely/shortid-test

The dependency seems pretty superficial, and I was able to remove it in our fork (https://github.com/optimizely/shortid/pull/2). If it's acceptable, I could submit that as a PR to this repo.

**Comment by ai** [comment]
Just stop using PrototypeJS. It is very dangerous thing, which could break most of npm packages.

**Comment by spencerwilson-optimizely** [comment]
OP and I maintain a piece of third-party JS that downstream users run on their sites. Your suggestion isn't viable in such cases as ours; namely, we require wide browser support, but also support in the presence of _users_ who may not fully appreciate the tradeoffs of PrototypeJS.

**Comment by ai** [comment]
Yeap, I understand that sometimes you don't have a option and must rely to unstable basement.

Try [Nano ID](https://github.com/ai/nanoid). It is even smaller and faster than shortid. But also it is much simplier and work without Array methods.

Do you need to support IE < 11? I can add docs for this case.
