### ISSUE TITLE
Shouldn't I use hat instead?

### ISSUE THREAD

**Issue by chardskarth** [dylang/shortid#115]
I came across this github project and immediately wondered if there are any difference with [hat](https://github.com/substack/node-hat)?

```
import hat from 'hat';

const getUID = hat.rack(16, 26, 4); // Not a real GUID/UUID format. 
getUID(); // generates non repeating random string
```

I'm no expert. It'd just be good to know the difference between these libraries.

**Comment by ai** [comment]
`hat` doesn’t use a hardware random generator so it is not secure and very predictable.
