### ISSUE TITLE
Document shortid's degree of cryptographic security

### ISSUE THREAD

**Issue by n-rook** [dylang/shortid#116]
I'm using shortid right now to generate short unique identifiers. (And it's great, thanks 😄) I was thinking of using shortid in places which require an ID which cannot be guessed, even by a dedicated, intelligent adversary. However, I am not sure if shortid is cryptographically secure or not. Is it? It would be nice to put this information in the README file.

I see that the shortids aren't "easily guessable", which is of course great, but that's a somewhat weaker guarantee than what I'm looking for.

Apologies if this information is already there!

**Comment by ai** [comment]
shortid is not secure and has no maintaince. Use [Nano ID](https://github.com/ai/nanoid) for it.

**Comment by n-rook** [comment]
If I send a PR to say "not cryptographically secure" in the README, do you think it'd get reviewed?

**Comment by ai** [comment]
Nope. This project has no maintaince 😏

This is why even in non-secure cases you should try to avoid it.

**Comment by n-rook** [comment]
I had a feeling you'd say that :) Well, thanks.

**Comment by ai** [comment]
I removed security promise bb58f3e

Feel free to send PR with better explanation

**Comment by n-rook** [comment]
Thank you, I opened a PR (#124)
