### ISSUE TITLE
[React-Native] Nanoid dependency is breaking react-native apps

### ISSUE THREAD

**Issue by eyalcohen4** [dylang/shortid#123]
Hey!
Great library, thanks.

I've updated today to 2.2.10 from 2.2.8, and the addition of nanoid cause crashes in a react-native environment, as it depends on the window object. ([see here](https://github.com/ai/nanoid/blob/master/random.browser.js)).

The error i'm reciving say: 
'can not find variable self', (which used in the previous link.)

I thought about checking if the type of self object is 
not undefined, but I'm not sure it's should be here or in the nanoid package, so let me know what you think.

Thanks again

**Comment by ai** [comment]
Thanks for the report. I am looking for the best solution. Hope it is not urgent.

**Comment by ai** [comment]
Does RN even has `global.crypto`?

**Comment by ai** [comment]
@eyalcohen4 Should be fixed in 2.2.11.
