### ISSUE TITLE
regression: shortid has hard dependency on crypto.getRandomValues() in browsers

### ISSUE THREAD

**Issue by jampy** [dylang/shortid#128]
The problem comes from commit f1fe429296d96744550ea2ba1a73e19a8e0a7498:

While your own code correctly checks for `crypto.getRandomValues()` availability you also include `nanoid/random`, which unfortunately [does not include this check](https://github.com/ai/nanoid/blob/d27740687a747c330fbbd1f8454d47edbf380e9a/random-browser.js).

MS Edge does not support `crypto` in web workers, so `shortid` does not work there.

**Comment by ai** [comment]
Why [this check](https://github.com/dylang/shortid/blob/f1fe429296d96744550ea2ba1a73e19a8e0a7498/lib/random/random-byte-browser.js#L7) was not run correctly in your case?

**Comment by jampy** [comment]
Probably because `random-byte-browser.js` is not used at all?

Apparently by webpack build uses `random-byte.js`, which relies on `nanoid`. At least I can't see any other reason why the `nanoid` code gets included in my build.

**Comment by ai** [comment]
I found the problem, wait few minutes

**Comment by ai** [comment]
Try `2.2.13`. If it will not work, can you put `console.log` to `random-byte.js` to be sure that webpack by some reason put it to the bundle?

**Comment by jampy** [comment]
Yes, that solves the problem! :-) Awesome, thanks a lot!

Can you publish the new version on NPM please?

BTW: Great work with shortid / nanoid!

**Comment by ai** [comment]
> Yes, that solves the problem! :-) Awesome, thanks a lot!

=^_^=

> Can you publish the new version on NPM please?

I already published 2.2.13

**Comment by jampy** [comment]
>I already published 2.2.13

Ah ok, npm *website* cache issue then ;-)

![image](https://user-images.githubusercontent.com/820758/44196769-1c9e1800-a13d-11e8-9223-06ff9a237014.png)
