### ISSUE TITLE
Could you explain how shortid generates unique IDs and maps them to a short string?

### ISSUE THREAD

**Issue by JamieCorkhill** [dylang/shortid#139]
I'm just wondering if you could explain the exact process by which you generate the unique ID - that is, what are the individual parts of the ID (do you use a timestamp, a MAC address, etc.?), how many bytes is that (non-shortened) ID, and then what is the process to convert or map that into a short string?

Thanks,
Jamie

**Comment by ai** [comment]
Nano ID does not use timestamp and bc MAC. Instead, they use hardware random numbers to prevent collisions. It is simplier and more secure way, this is why shortid is deprecated.

Short ID shuffle alphabet by Math.random (which is not hardware random) and then took hardware random symbols from this alphabet. ID length depends on how long your program works and how fast you generate new number.

**Comment by JamieCorkhill** [comment]
Thanks. Indeed, I've never responded to a GitHub comment by email before, so I forgot it would include the signature. I'll edit it out on the website later.

Jamie Corkhill
Full Stack Web & Mobile Developer

CONFIDENTIALITY NOTICE: This message, including any attachments, may contain confidential, proprietary, privileged and/or private information. The information herein is intended only for the use of the individual, entity, or named recipient(s) designated above. If you are not the intended recipient of this message, please notify the sender immediately, and delete the message and any attachments without saving, reading, copying, forwarding, or otherwise retaining or disclosing any of its contents. Any disclosure, reproduction, distribution or other use of this message or any attachments by an individual or entity other than the intended recipient is strictly prohibited.

________________________________
