### ISSUE TITLE
ShortID does not generate CSSSelector id friendly

### ISSUE THREAD

**Issue by gabycperezdias** [dylang/shortid#148]
As can be seen in this (https://medium.com/front-end-weekly/css-selector-for-element-which-have-numbers-as-class-name-b6a089989199) for an ID to be cssSelector friendly it must start with a letter, an underscore or a hyphen.
This causes some issues such as (https://stackoverflow.com/a/51396346/3326192) where querySelector, native from javascript that uses a CSS Selector, does not work when the ID starts with a number.

Currently I can't find a way to work around this, mainly because, even if I try to remove all numbers from the set of chars I would have to replace all of them with special chars since the characters method needs to have 64.

Could you please help me? Thanks

**Comment by ai** [comment]
`shortid` is deprecated, don’t use it. Move it [Nano ID](https://github.com/ai/nanoid/).

Nano ID already has the note in the docs about IDs: https://github.com/ai/nanoid/#react

```js
<input id={'id' + this.id} type="text"/>
```
