### ISSUE TITLE
Can I use findbyid populate and equals?

### ISSUE THREAD

**Issue by luluhoc** [dylang/shortid#149]
Hey,

I want to use shortid but I would love to know if it is possible to use equals() and how I can embed just the ids, for example, I have a user and I want to store in user schema all the liked posts (favShort in my schema) and then populate them this is my schema that is using object id for now

Also can I use findbyid with it?
``` const UserSchema = new mongoose.Schema({
  _id: {
    type: String,
    default: shortid.generate,
  },
  username: {
    type: String,
    lowercase: true,
    unique: true,
    required: true,
  },
  password: {
    type: String,
  },
  showNsfw: { type: Boolean, default: true },
  timezone: { type: String, default: 'CEST' },
  favShort: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Shortcut',
  }],
  email: {
    type: String,
    lowercase: true,
    unique: true,
    required: true,
  },
  permissionLevel: { type: Number, default: 1 },
  role: {
    type: String,
    enum: ['member', 'moderator', 'premium', 'admin'],
    default: 'member',
  },
  country: String,
},
{
  timestamps: true,
}); ```

**Comment by ai** [comment]
> I want to use shortid 

Don't use shortid, it is deprecated. Use Nano ID.

> Also can I use findbyid with it?

Nano ID (and shortid) generates simple string. I have no big experience with your DB, but you can use DB’s docs.
