### ISSUE TITLE
Collision/ Duplicate Ids getting Generated In our Production with this module

### ISSUE THREAD

**Issue by pssvenkatrao** [dylang/shortid#150]
I am using the default setting
shortid.characters("0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_");
shortid.generate().substring(0, 5);
I am seeing the duplicate IDs generating and resulting in failure when I have short id as unique index while saving in DB.

We are running the code in 5 PODs in each of kubernetes clusters.. Please suggest.

**Comment by ai** [comment]
1. `shortid` is deprecated. Use [Nano ID](https://github.com/ai/nanoid/).
2. 5 symbols are not enough to prevent collisions in complex systems.
3. Here is [ID length and collisions calculator](https://zelark.github.io/nano-id-cc/) to choose the best length for you.
