### ISSUE TITLE
Use short ID for SQL table names.

### ISSUE THREAD

**Issue by ashoksahoo** [dylang/shortid#152]
I want something which satisfies this for generating a temporary table name, for a specific ETL  operation id. I can replace the dash with a dollar and keep generating until it satisfies the Rule-1 and also maybe a check for rule 5. 

Can we get a config where we can set these kinds of rules?

> Standard SQL identifiers adhere to a set of rules and must:
> - Begin with an an ASCII single-byte alphabetic character or underscore character, or a UTF-8 multibyte character two to four bytes long. 
> - Subsequent characters can be ASCII single-byte alphanumeric characters, underscores, or dollar signs, or UTF-8 multibyte characters two to four bytes long.
> - Be between 1 and 127 bytes in length, not including quotes for delimited identifiers.
> - Contain no quotation marks and no spaces.
> - Not be a reserved SQL key word.

**Comment by ai** [comment]
Don’t use shortid. It has an architecture problem and does not maintain anymore. Switch to [Nano ID](https://github.com/ai/nanoid/).

For table names, [switch alphabet](https://github.com/ai/nanoid/#custom-alphabet-or-length) to alphabetic character (A…Z) or underscore character. I recommend to add some prefix to avoid using reserved SQL key word.
