### ISSUE TITLE
Option to provide less than 64 characters?

### ISSUE THREAD

**Issue by JoshMcCullough** [dylang/shortid#158]
I'd like to generate ids with only alphanumeric characters, but that is not possible because there are only 62 of those characters. I realize that this affects the total number of possible unique ids, but also realize that it won't matter in my case, and would be opt-in.

**Comment by ai** [comment]
This project is deprecated.

Use [Nano ID](https://github.com/ai/nanoid/) which is smaller, faster and allow to change alphabet.

**Comment by JoshMcCullough** [comment]
Thank you.
