### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by EgoAleSum** [dylang/shortid#25]
It would be great to use shortId on a web browser!

Compiling it to a single JS library is not complicated, thanks to browserify (with the 'debowerify' transform, or it will screw up other people). A sample Grunt task:

`````
js
browserify: {
	dist: {
		files: {
			'shortid.js': ['lib/shortid.js']
		},
		options: {
			transform: ['debowerify'],
			browserifyOptions: {
				paths: ['lib/']
			}
		}
	}
}
`````

The biggest obstacle is that `lib/encode.js` is using the `crypto` module to generate random bytes. Do you think it's possible to add an alternative to that to run on a web browser? I can provide PR if you need help with this.

**Comment by dylang** [comment]
I now use browserify for all my projects, but I wasn't using it when shortid was created. 

I'm happy to accept a PR to make using shortid easier/more flexible for browser usage. 

I don't have a good reason to use `crypto`, it just felt nicer.

**Comment by EgoAleSum** [comment]
I'm happy to contribute, but I wish you could give me any advice on what crypto library I should implement on the client side, if you have any preference.

**Comment by flesler** [comment]
Isn't it just some random bytes? can't change it to something that doesn't rely on any crypto library but rather Math.random() or something like that?

**Comment by EgoAleSum** [comment]
Not exactly. crypto.randomBytes() generates "cryptographically strong pseudo-random data". It's more random than just Math.random(). For the purposes of shortid, which doesn't check for duplicates but just relies on probability, I'm not sure Math.random() could be enough, IMHO.

**Comment by dylang** [comment]
It's just random bytes, `Math.random` should be enough.

**Comment by pekeler** [comment]
+1

**Comment by pekeler** [comment]
Crypto is part of node. So the dependency on crypto prevents me from using shortid with other JavaScript runtimes (on the server).

**Comment by EgoAleSum** [comment]
Hence my PR #28

**Comment by pekeler** [comment]
@EgoAleSum your PR assumes the availability of crypto on the server which isn't helping me.

**Comment by pekeler** [comment]
alternative PR #31

**Comment by EgoAleSum** [comment]
No I don't assume that. Check the code. It uses Crypto *IF AVAILABLE* with fallbacks to the Web Crypto APIs and to Math.random

**Comment by pekeler** [comment]
@EgoAleSum again: I'm talking about the server-side.
https://github.com/EgoAleSum/shortid/blob/browser-support/lib/encode.js#L4 is false
so it goes to
https://github.com/EgoAleSum/shortid/blob/browser-support/lib/encode.js#L21
and blows up in
https://github.com/EgoAleSum/shortid/blob/browser-support/lib/encode.js#L22
when crypto is not available

**Comment by EgoAleSum** [comment]
Ok, I'll fix it

**Comment by EgoAleSum** [comment]
Fixed in the last commit on patch #28 .

**Comment by EgoAleSum** [comment]
Fixed in the last commit on patch #28 .

@dylang  any news wether you'll accept the PR?

**Comment by Hiswe** [comment]
It will be great if it was on the browser :)
Any news about this?

**Comment by EgoAleSum** [comment]
@Hiswe The patched PR was submitted almost two months ago, now it's up to @dylang :)
