### ISSUE TITLE
hi, about the efficiency issue.

### ISSUE THREAD

**Issue by chloetina** [dylang/shortid#26]
I just noticed that we should override the _id field in order to use this short URL

```
_id: {
    type: String,
    unique: true,
    'default': shortId.generate
},
```

So, it will change _id ObjectID type to String type, I just wonder is there any big efficiency difference after using this?

**Comment by dylang** [comment]
I don't know. This is a good question for Mongo support. You could also do benchmarking and find out if it makes a difference with your server and usage.

**Comment by chloetina** [comment]
I've tested after I posted this question here, the searching by String type field will lead a BasicCursor type which mean scan all the doc every time, we can resolve it by indexing it but this means we need more space to store index. But if we search by _id (ObjectID) will get a BtreeCursor is more efficient. Actually it will lead a big difference efficiency.  :)

**Comment by dylang** [comment]
Makes sense, thanks!
