### ISSUE TITLE
How to change so that it generates valid DOM ids?

### ISSUE THREAD

**Issue by jessegrosjean** [dylang/shortid#29]
DOM ids need to start with a-zA-Z, I'm wondering what the best way to enforce this constrain in shortid would be. Right now I've modified the generated function like this:

```
function generate() {

    var seconds = Math.floor((Date.now() - REDUCE_TIME) * 0.001);

    if (seconds === previousSeconds) {
        counter++;
    } else {
        counter = 0;
        previousSeconds = seconds;
    }

    var str = encode(alphabet.lookup, version),
        code = str.charCodeAt(0);
    while (!((code >= 65) && (code <= 90)) && !((code >= 97) && (code <= 122))) {
        str = encode(alphabet.lookup, version);
        code = str.charCodeAt(0);
    }

    str = str + encode(alphabet.lookup, clusterWorkerId);
    if (counter > 0) {
        str = str + encode(alphabet.lookup, counter);
    }
    str = str + encode(alphabet.lookup, seconds);

    return str;
}
```

The change is that when I encode the version I keep "encoding" until I get something that starts with a letter. This seems to work, but I'm wondering if there's some smarter way.

Jesse

**Comment by flesler** [comment]
```js
var id = 'i' + shortid.generate();
```
Done :D

**Comment by jessegrosjean** [comment]
@flesler Heh... I was doing that. But then all my ids had an 'i' in front and that looked a little weird! I also didn't want to break the `decode` method, though in truth I'm not using it and am not likely too. But you are probably right, that's the simplest and probably smartest way.

**Comment by dylang** [comment]
Don't worry about breaking decode. It's mainly for internal tests.
