### ISSUE TITLE
what would be the drawback from using this as a random generator?

### ISSUE THREAD

**Issue by anthonyettinger** [dylang/shortid#30]
what would be the drawback from using this as a random generator?

```Math.random().toString(35).slice(2, 12);```

**Comment by EgoAleSum** [comment]
1. That code uses a more limited charset ([a-z0-9]), which means you can pack less information (ie. less randomness) in the same length

2. Math.random() uses a non-cryptographically strong PRNG. See my comment here: https://github.com/dylang/shortid/issues/10#issuecomment-70420180
