### ISSUE TITLE
Does shortid generates really unique ids?

### ISSUE THREAD

**Issue by skotchio** [dylang/shortid#36]
Sorry for the asking questions here but I need to know about uniqueness if ids generated by shortid. Is it really unique ids or in some cases they could repeats? I need to provide completely unique ids because it's very critical for my application.

**Comment by dylang** [comment]
Every id is going to be unique. Id's are generated with a combination of a timestamp, counter, and crypto-safe random characters (to avoid two machines from generating the same random characters at the same time). 

It could repeat is if you change the `seed` or `alphabet`, so once you set those never change them (these functions are documented in the README). If you add or remove characters from the generated id it is theoretically possible to become a repeated id, so I strongly recommend not changing the generated id unless you add characters that are not in the alphabet it uses.

**Comment by skotchio** [comment]
Thanks for the reply. So if I will use this module like the following (I mean without changing):

    var shortid = require('shortid');
    console.log(shortid.generate());
    //PPBqWA9

That I'll get 100%  unique ids

**Comment by dylang** [comment]
That looks good for unique ids!

**Comment by igor9silva** [comment]
What if there are no more possibilities of generating an unique ID? What does it do? @dylang

**Comment by flesler** [comment]
It never runs out of IDs, they just get longer

**Comment by dylang** [comment]
@flesler is correct, they just get longer over time.

**Comment by thelinuxlich** [comment]
Does this means there is zero chance of collision?

**Comment by igor9silva** [comment]
I think so @thelinuxlich.
Since 17 Jun (my last comment) my IDs got much longer, but no collision.

**Comment by thelinuxlich** [comment]
@igor9silva how many chars?

**Comment by igor9silva** [comment]
Around 9, but normally 8.
