### ISSUE TITLE
ID character limit

### ISSUE THREAD

**Issue by drag0** [dylang/shortid#39]
Could it be possible to request from shortId to generate IDs that are, for example, between 7 and 10 characters long? Or some other interval?

**Comment by imkevinxu** [comment]
+1

**Comment by AleksMeshkov** [comment]
+1

**Comment by Fleischers** [comment]
I would also prefer this option to be able to generate only 5 characters

**Comment by a1ananth** [comment]
+1

**Comment by dylang** [comment]
I appreciate your request, but with the small size you will risk of duplication. We can't avoid that with smaller sizes.

**Comment by Fleischers** [comment]
@dylang My point was to be able to generate smaller id and check duplication by application itself elsewhere. In my case it was checking the database.
Anyway, I ended up with my own solution, so thanks for your answer on this issue.

**Comment by dylang** [comment]
@Fleischers if you are going to check your db for duplication, you might as well use a random string of desired length.

Here's one such module, found by searching npm:

https://github.com/klughammer/node-randomstring

If you find this helpful, I can add it to the readme.

**Comment by Fleischers** [comment]
@dylang That is what I tried to find. 
Do not bother about it, I suppose that I am the only one who had problem to google npm by myself. I appreciate your help, but I already managed to complete my task

**Comment by dylang** [comment]
@Fleischers you are not alone, npm's search is something they agree they still have a lot of work to improve.

I used http://node-modules.com/ to find that module.
