### ISSUE TITLE
How to use shortid with brunch.io?

### ISSUE THREAD

**Issue by ceremcem** [dylang/shortid#44]
I'm using Brunch.io and I'm trying to use shortid in client side. Since `shortid` claims that it's compatible with browserify, I tried many things including
- Browserify the module with the following command:
  
  ```
  browserify -r ./index.js:shortid > /project/vendor/shortid.js
  ```
- and use it in the application code: 
  
  ```
  var shortid = require("shortid"); 
  ```

Web page is giving the following error: 

```
 TypeError: require.register is not a function
 TypeError: loaderPath.indexOf is not a function
```

**Comment by gtlambert** [comment]
@ceremcem did you ever find a solution to this? I'm totally stuck trying to use `shortid` with `browserify` right now

**Comment by ceremcem** [comment]
Nope... I'm on my way to switch to webpack for several issues including this one. But, for now, as a workaround, you may use this code: https://github.com/ceremcem/aktos-scada/blob/master/vendor/base-libraries/uuid4.js

**Comment by dylang** [comment]
Sorry you are having this issue.

If you can provide a fix and a test as a PR I'm happy to apply it.
