### ISSUE TITLE
Module is not stateless

### ISSUE THREAD

**Issue by ash2k** [dylang/shortid#48]
If I'm reading it correctly, `shortid.characters()` method mutates the module state so it is impossible to use from different places in code that need different character settings. Do you plan to support this usecase?

**Comment by dylang** [comment]
Hi @ash2k, that is correct. Can you help me understand the reason you would like this? I did this to make the library easier to use.

**Comment by ash2k** [comment]
I wanted to use the module in several different parts of the system that need different settings for the IDs.

**Comment by dylang** [comment]
That makes sense. As I'm sure you know, it's generally not a good practice for modules to have state. 

If you to make a PR to fix this issue I'd be happy to consider it. Ideally it wouldn't change the way the API works today, for example, if you want a stateless instance, maybe that be some new method like

```
var shortid1 = shortid.instance();
var shortid2 = shortid.instance();
```

(The method name doesn't have to be `instance`.)

**Comment by k00k** [comment]
+1 I just came here looking for this feature. I have a couple different things in my application that each use "separate" shortids. For example, image filenames in one place and reset password tokens in another. Would ideally allow for multiple instances or namespaces.

**Comment by dylang** [comment]
@k00k If you don't mind using the same alphabet for both then you can use `shortid` as it is now.

**Comment by k00k** [comment]
@dylang Same alphabet is fine. So are you saying that if I use shortid in multiple places, for example `var x = shortid.generate; var y = shortid.generate;` that the generation happens independently? So if `var x` gets called 2 million times and `var y` only 10 times after `var x`, `var y` will have nice simple short ids? I ask because I know that the shortids get longer as time goes on. That's fine for a given "instance", but would like to avoid new instances starting out with those longer ids. If that makes sense.

**Comment by dylang** [comment]
@k00k the length of the `shortid` will grow very slowly with time, but not with usage. You'll have to call it hundreds (maybe thousands) of times a second noticeably grow the size.

**Comment by njakob** [comment]
+1 I'm also looking for this feature, would be great to simply expose a constructor and use a default instance of it otherwise.

**Comment by snimavat** [comment]
If we make shortid stageful then its possible that differerent instances of shortid can generate the sameid right? as long as the different instances are used for different usecases it should not be an issue otherwise there could be duplicates

**Comment by ai** [comment]
@snimavat yeap, but because shortid is based on RNG different instances will generate unique IDs too (if you set different `worker`). So we don’t loose anything here.

**Comment by snimavat** [comment]
Oh yea, there's workedid

**Comment by ai** [comment]
This library will not change API.

Use [Nano ID](https://github.com/ai/nanoid). It has stateless API.
