### ISSUE TITLE
Is it safe to change REDUCE_TIME in source code?

### ISSUE THREAD

**Issue by ybian** [dylang/shortid#53]
Sorry if this is more a question than an issue.

I see the following lines in the source code:

```
// Ignore all milliseconds before a certain time to reduce the size of the date entropy without sacrificing uniqueness.
// This number should be updated every year or so to keep the generated id short.
// To regenerate `new Date() - 0` and bump the version. Always bump the version!
var REDUCE_TIME = 1426452414093;
```

Is it safe to edit this file directly and just change the REDUCE_TIME to the current time? What's the recommended practice? 

If I don't change it the ids generated are 9 characters long. If I change it to "now" the ids generated are only 5 characters long, but they could not pass the `isValid()` check which is a concern to me.

**Comment by flesler** [comment]
If you change `REDUCE_TIME`, you need to also increment the `version`. It will be safe then.
You might get collisions if the original code also increments the version and you revert back to it.

As long as you use your modified version it'll be fine.

**Comment by ybian** [comment]
Got it. I guess I would not modify this by myself. I would rely on the official distribution to update this value regularly while bumping the version.

**Comment by flesler** [comment]
You could suggest @dylang to bump it, maybe it's time :D

**Comment by billinghamj** [comment]
I think it'd be good to bump this now. The generated IDs have started to become longer due to the large timestamp component

**Comment by billinghamj** [comment]
Yes, it was about a year ago that it was last bumped (mid-May 2015), so it's about time.
