### ISSUE TITLE
random-byte-browser.js throws exception in web workers (threads)

### ISSUE THREAD

**Issue by b3devs** [dylang/shortid#56]
In random-byte-browser.js, the following line throws an exception because 'window' is not defined in web workers.

var crypto = window.crypto || window.msCrypto; // IE 11 uses window.msCrypto

The workaround is kind of ugly:

>if (global.window === undefined) {
>  global.window = {};
>  ShortId = require('shortid');
>  delete global.window;
>}

Possible fix for the offending line:

>var crypto = (window !== undefined
>                     ? window.crypto || window.msCrypto; // IE 11 uses window.msCrypto
>                     : null);

**Comment by dylang** [comment]
Fixed by #64
