### ISSUE TITLE
shortid.worker() question

### ISSUE THREAD

**Issue by herkyl** [dylang/shortid#57]
I understand that setting the worker ID is required when having multiple processes. Is this also required when the processes are on the same machine? If so would it make sense for shortid to use `process.pid` internally?

**Comment by dylang** [comment]
Hi @herkyl, thanks for your question.

That's a great idea that I hadn't thought about. A concern is that `process.pid` can be a large number, and that could effect the size of the id. What do you think?

**Comment by dylang** [comment]
Fixed with #64

**Comment by herkyl** [comment]
Hm, I didn't think of that.
Personally I just pass a number from 0 to N to each process on a single machine. I guess it's up to you on how you want to manage this :)

**Comment by kamilml** [comment]
Hi guys. For exmaple, if I am using some instances of my app in a cloud service like now.sh (I am not sure if this is an only one server or different servers for each instance) with 20 processes in total.
I have to pass `shortid.worker(0-16)` ? Then I just can numbered 17 instances.

**Comment by ai** [comment]
Should be fixed by using `cluster` API https://github.com/dylang/shortid/pull/94
