### ISSUE TITLE
Collision chance

### ISSUE THREAD

**Issue by franciscop** [dylang/shortid#58]
I think it would be nice to have a table with the collision chance as extra information in the README. If I'm not mistaken, the math is:

- 64 options per character (since there are 64 different options)
- up to 14 characters (however I'm unsure on what this depends)

Therefore, the number of options is N = 64 ^ 14. According to [this blog post](http://preshing.com/20110504/hash-collision-probabilities/), the chance of a collision is *similar* to `100 * (1 - e ^ (-k^2 / (2 N)))`

In a table it should look like:

| ids generated          | chance of collision (%)      |
|-----------------------------|--------------------------------------|
| 1                               | ~0                                         |
| 10^4                         | 2.6e-16                                |
| 10^5                         | 2.6e-14                                |
| 10^6                         | 2.6e-12                                |
| 10^7                         | 2.6e-10                                |
| 10^8                         | 2.6e-8                                  |
| 10^9                         | 2.6e-6                                  |
| 10^10                       | 2.6e-4                                  |
| 10^11                       | 0.026                                   |
| 10^12                       | 2.55                                     |
| 10^13                       | 92.45                                   |
| 10^14                       | 100                                      |

Calculated with [Wolfram Alpha](http://www.wolframalpha.com) using [this formula](http://www.wolframalpha.com/input/?i=100+*+%281+-+e+^+%28-%2810^X%29^2+%2F+%282+*++64+^+14%29%29%29) (replace X)

**Comment by franciscop** [comment]
Also this could help [this other issue](https://github.com/dylang/shortid/issues/38) to compute the chance.

**Comment by franciscop** [comment]
Note that 10^30 (which is safe enough for most applications) is 1.000.000.000.000.000.000.000.000.000.000 elements, already taking into account the birthday problem

**Comment by billinghamj** [comment]
Are you assuming that the characters are generated randomly? In this library in fact, they are not.

I would still be interested in collision analysis, but you'll need to fully understand how the values are generated.

**Comment by franciscop** [comment]
Yes, I was assuming it. I didn't enter into the library as I'm not used to cryptography code, that was a best-case estimation and opening the issue hoping that someone with more knowledge about this could correct me and provide a better analysis :+1:

**Comment by thelinuxlich** [comment]
The id grows indefinitely or stops at 14 characters?

**Comment by flesler** [comment]
Grows indefinitely within the same second and then resets to minimum (currently 9) so the length depends on how many you request per second.

I just did a test with the latest version, here's how many IDs you can generate **in the same second** before it needs to increase size. 

Length | # of IDs | Total # of IDs
------ | ------ | ----
9|1|1
10|15|16
11|240|256
12|3840|4096
13|61440|65536
14|34464|100000

So... you need to generate more than 4 IDs **per millisecond** to get IDs longer than 12 chars. As you can see, numbers are high.

Github is not letting me upload the (zipped) CSV file with the 100k IDs even though ZIP is supposed to be accepted, so, here's the code to generate it if you're interested:

```js
var shortid = require('shortid');

// Make sure all happens within the same second
var now = Date.now();
Date.now = function() {
	return now;
};

var stream = require('fs').createWriteStream('shortids.csv');
stream.write('#,length,id');
for (var i = 1; i <= 1e5; i++) {
	var id = shortid.generate();
	stream.write('\n' + i + ',' + id.length +',' + id);
}
```
Hope this finally clears out how it works.

**Comment by thelinuxlich** [comment]
So there is no birthday paradox with these shortids, right?

**Comment by billinghamj** [comment]
As can be seen above, shortid does not generate its output randomly. It uses a combination of the time, host, an incrementing number, and a little bit of extra randomness just in case.

The incrementing number is guaranteed to be atomic, because JavaScript does not do threading.

However, it is very important that you're aware of whether multiple processes are running. If you have more than one process running without setting unique shortid worker IDs, and a shortid is generated on both in the same second, the chance of a collision is about 1 in 4.

Thus, it is very important that you call `shortid.worker` with a unique number between 0-15 if you're running multiple processes.

Additionally, if you're using some kind of alternative JS host which supports threading with non-locked shared memory, you may have problems caused for the same reason.

**Comment by rgrove** [comment]
> - 64 options per character (since there are 64 different options)
> - up to 14 characters (however I'm unsure on what this depends)
>
> Therefore, the number of options is N = 14 ^ 64.

Isn't this backwards? If there are 64 possibilities per character, then shouldn't an id that's 14 characters long have 64 ^ 14 possible values?

For example, with an id length of 2, 64 ^ 2 yields 4,096 possibilities, whereas 2 ^ 64 yields 18,446,744,073,709,551,616 possibilities, which seems obviously wrong.

While still a lot, 64 ^ 14 is a vastly smaller number than 14 ^ 64. Hopefully someone with a math background (that's not me) can check my numbers here. :smile:

**Comment by flesler** [comment]
Yes, it's 64 ^ 14, meaning 64*64*64*64*64*64*64*64*64*64*64*64*64*64.

Whatever the numbers, I've shown in my previous comment that even reaching IDs 13 char long requires quite a high demand of IDs per second.

And regardless of length, collisions are impossible within a single process or otherwise if worker id is used correctly. I think this issue can be closed.

**Comment by franciscop** [comment]
Oops, completely missed it, for sure it's 64^14. I'll update the original post
