### ISSUE TITLE
I can't update a document has _id is shortid type

### ISSUE THREAD

**Issue by ntaback26** [dylang/shortid#63]
Please help me:
Cast to ObjectId failed for value "VyNE6cP2l" at path "_id"

**Comment by manuel-di-iorio** [comment]
Did you defined your schema _id path so:

    _id: {
        type: String,
        unique: true,
        'default': shortid.generate
    }

Notice the String type and not ObjectId

**Comment by dylang** [comment]
Thanks for answering the question @manuel-di-iorio!
