### ISSUE TITLE
ID length doesn't change

### ISSUE THREAD

**Issue by sircharleswatson** [dylang/shortid#67]
First, for my use-case, IDs won't be generated in mass at one time.

IDs will be generated whenever a user asks for one so there could be a lot of time between generations.

For that case, the `shortid.generate()` will _only_ produce IDs of one length (6 - which is [another issue](https://github.com/dylang/shortid/issues/66))

Here's an example:

```
setTimeout(function() {
    console.log(shortid.generate())
    setTimeout(function() {
        console.log(shortid.generate())
        setTimeout(function() {
            console.log(shortid.generate())
            setTimeout(function() {
                console.log(shortid.generate())
                setTimeout(function() {
                    console.log(shortid.generate())
                }, 30000)

            }, 30000)

        }, 30000)

    }, 30000)

}, 30000)
```

With 30 seconds between each generation, you're stuck on creating 6 char long IDs.

**Comment by flesler** [comment]
What's wrong with them being 6 char long?

**Comment by sircharleswatson** [comment]
@flesler Well _only_ having them be 6 char long significantly increases the chance of duplication. Which the varying length of 7 to 14 (as stated in the readme) is supposed to avoid.

**Comment by flesler** [comment]
@sircharleswatson there is no chance of duplication within a single or machine nor globally if you use `shortid.worker()` properly. There are some closed issues with explanations of that

**Comment by flesler** [comment]
Here https://github.com/dylang/shortid/issues/58#issuecomment-166401161
