### ISSUE TITLE
Not An Issue - How is each unique?

### ISSUE THREAD

**Issue by psmod2** [dylang/shortid#68]
Hi,

Not an issue here - more of a question. Wasn't sure where to ask.

Anyway, I want to know how does the the package ensure the ID generated is unique each time? Does it keep some sort of record? Or is it doing something like using the 1/10000 millisecond of time?

Look forward to your response (as I'm very keen to implement).

Thanks.

**Comment by sujaykathrotia** [comment]
Yep!

https://github.com/dylang/shortid/blob/master/lib/index.js#L37

**Comment by flesler** [comment]
Here I explained a bit how it works 

https://github.com/dylang/shortid/issues/58#issuecomment-166401161

The minimum length should be smaller now due to a bump in REDUCE_TIME but the the rest is pretty much the same.

**Comment by psmod2** [comment]
Ok - makes sense, so it uses a very short amount of time ( *0.001) and where there are more than 4 requests per milliseconds, it automatically increases the ID length?

**Comment by flesler** [comment]
No. It concatenates the ID version, a cluster ID, the current timestamp without milliseconds and a counter that increases for each ID and resets every second.

Each component is a number encoded to a string along with some random bits.

**Comment by psmod2** [comment]
So what happens if I get 10 requests in a millisecond?

**Comment by flesler** [comment]
IDs just keep getting longer (the last component). There are never collisions.

**Comment by psmod2** [comment]
Ah sorry, missed that bit 'concatenates' - makes sense now.
Thanks!

**Comment by D7Torres** [comment]
Sorry to reopen. Would be a collision possible if the application is restarted?
Thank you in advance!

**Comment by flesler** [comment]
Only if it generates IDs before and after the restart within the same second and even if that unlikely situation happens, there are random components will make it somewhat unlikely that there will be a collision then. I think it's not a problematic situation even then.
