### ISSUE TITLE
RNG appears to be predictable, have short period

### ISSUE THREAD

**Issue by XMPPwocky** [dylang/shortid#70]
The random number generator used- https://github.com/dylang/shortid/blob/master/lib/random/random-from-seed.js - is a linear congruential generator. It also has only 32 bits of state; this creates two problems.

One- the output sequence of this generator has a period of, at maximum, 2**32 . Because of the birthday paradox, one would expect to see a collision after around 80,000 short IDs being generated if they were truly random; luckily, because of the sequential nature of this generator, this is mostly not the case (repeated outputs don't happen, because if they did the entire generator would repeat). Still- there are only about 4 billion possible short IDs, and if 4 billion short IDs are generated, then they will start repeating!

Two- because the state is so small, it is bruteforceable. An attacker who can observe a few short IDs can try all 4 billion possible generator states, and discover which state generated those short IDs. The attacker can then predict all future IDs generated!

**Comment by ai** [comment]
@XMPPwocky sure. It is a big problem. Can you recommend some ways to fix it?

**Comment by ai** [comment]
I think https://github.com/dylang/shortid/issues/85 is related

**Comment by ai** [comment]
I didn’t find the way how to fix it in `shortid` with existed API, so I created the new project with guaranteed uniformity:
https://github.com/ai/nanoid
