### ISSUE TITLE
Comparison with hashids.org?

### ISSUE THREAD

**Issue by olalonde** [dylang/shortid#71]
Hi, was wondering quickly what was the difference if any between this module and https://github.com/ivanakimov/hashids.node.js. Thanks!

**Comment by radeno** [comment]
I don't do deep comparison. But as i can see, ShortID is random one way unique random generator. 
HashIDS is hash generator based on numeric value and salt. You can decode it to original value.
Both works similar, but ShortIDS is really unique because don't depends on numeric value.
