### ISSUE TITLE
Ask for officially pre-built files for browser usage as distribution purpose

### ISSUE THREAD

**Issue by PeterDaveHello** [dylang/shortid#73]
Hi @dylang,

I'm Peter from @cdnjs, since there are some requests from the users to ask we host this awesome lib be hosted on our CDN (cdnjs/cdnjs#8602 cdnjs/cdnjs#6736), I am wondering if it's possible to provide the official dist files for browsers in the npm package? So that we can easily host this lib, and users/developers can get the files easier, both from npm or CDNJS, what do you think?

Best,
Peter

**Comment by ai** [comment]
Hi. Right now we have many new and better ID libraries. So I am closing this issue.

For instance, I recommend adding [Nano ID](https://github.com/ai/nanoid/blob/master/index.browser.js). It smaller and safer.
