### ISSUE TITLE
Perfect for MongoDB ?

### ISSUE THREAD

**Issue by quocnguyen** [dylang/shortid#74]
I want to use shortid as a replacement for mongo objectid, however as far as I know, objectid is both unique and sortable.

On the other hand shortid is `Non-sequential` , does it mean that shortid is not sortable ?

**Comment by giter** [comment]
agree

**Comment by flesler** [comment]
I asked in the past to be able to disable the random component if desired, shortids "source" (numbers) is more or less generated in chronological order. It becomes non-sequential one the random bits are introduced

**Comment by ai** [comment]
Yeap, this library’s IDs is not sortable.
