### ISSUE TITLE
Throttle short id generate to keep length low

### ISSUE THREAD

**Issue by angelo0000** [dylang/shortid#75]
My understanding is that the length of the shortid generated is based on how many per ids you generate in a given timeframe.  The more you generate the longer the id is to prevent collision.

In my app I generate ~2M keys in a short period of time while I am building a tree.  I am storing those shortids in a text field using a materialized path approach for mongo trees.  My core issue is I am bumping the 1024 key index limit on a field for mongo and I am looking for ways to give me some more headroom.

In looking at my generated shortids they quickly become length 12 even though at the end of the day I only need 2M keys.  What is the requests/time I need to keep the key generation down to in order to keep the shortid generated at 9 chars?

**Comment by angelo0000** [comment]
I am also using 2.0.0.  I saw a comment somewhere that the REDUCE_TIME was bumped to keep the key length low.  If I upgrade to the latest will my initial keys be shorter than the 9 they are now?

**Comment by angelo0000** [comment]
I installed the latest and with a small test I see that throttle the id generation does keep the generated id shorter.  If I throttle the key generation at 10 ms between generations for a large set of say 5,000 keys I get keys of 9 or 10 in length mostly. With a 1ms delay between generations I get keys of 10 or 11 in length.  With a long delay of 100ms between generations I get keys of 8 and 9 in length.  With no delay I get keys mostly 11 and 12 in length which is what I am seeing in production where we generate keys in batches of 20k.  

I can do the throttling and that will certainly help me save many bytes.  Having 60+ keys on an index field with length of 10 vs 12 per key will save me 120 bytes and let me store an additional 12 keys which is very helpful.

Is there a way to make the generated ids shorter than the 8/9 it starts with?

**Comment by ai** [comment]
I didn’t find the way how to fix it in `shortid` with existed API, so I created the new project with guaranteed uniformity:
https://github.com/ai/nanoid
