### ISSUE TITLE
How do i limit the generated id to 10 digits ?

### ISSUE THREAD

**Issue by davibe** [dylang/shortid#76]

**Comment by flesler** [comment]
You can't , they get longer based on how many you generate per second.

If you're willing to risk some collisions, you can do:
```js
var id = shortid.generate().slice(-10);
```
If you are going to crop, it's better to crop the start rather than the end to get less collisions.

**Comment by ai** [comment]
shortid doesn’t have API to change ID length. Use [Nano ID](https://github.com/ai/nanoid)
