### ISSUE TITLE
Consistently and immediately hitting  duplicates.

### ISSUE THREAD

**Issue by HarrisRobin** [dylang/shortid#77]
So I have replaced the mongodb generated ID with this one but I am consistently hitting a duplicate for every document after my first one.

I am clearly doing something wrong, because the same ID is being generated over and over again and I get ```MongoError: E11000 duplicate key error```

My code:
```
var schemaOptions = {
  toJSON: {
    virtuals: true
  }
};
var transactionSchema = new mongoose.Schema({
  _id: {
    type: String,
    'default': shortid.generate()
  },
  createdAt: {
    type: Date,
    expires: '7d',
    default: Date.now
  }
}, schemaOptions);
```

running:
**node: v6.4.0
mongoose: 4.4.8
shortid: 2.2.6**

**Comment by HarrisRobin** [comment]
UPDATE: I could not hit duplicates once I implemented retries on collision, however I am concerned. Why do I need to do retries? as soon as I remove the retries, I hit a collision on my second try again and consistently.

**Comment by flesler** [comment]
Never used mongoose, but just from pretending I understand it, shouldn't it be?:
```js
'default': shortid.generate
```

**Comment by HarrisRobin** [comment]
@flesler you are right. 

Thanks!
