### ISSUE TITLE
Scaling to more than 16 workers?

### ISSUE THREAD

**Issue by olalonde** [dylang/shortid#79]
I guess this module isn't suitable if you have more than 16 processes?

**Comment by nikwen** [comment]
Can this somehow be changed?

**Comment by ai** [comment]
You can always put worker ID to record ID:

```js
const id = worker + ':' + shortid()
```

**Comment by nikwen** [comment]
I feel like this could be solved better.

There could be a method to set the max worker count that is being dealt with, which determines the next higher number in the series (15, 255, 4095, ...) = (16^n - 1)_n, and then one would have to modify `encode()` to resemble the following, where the number determined above is passed as max:

```
function encode(lookup, number, max) {
    var loopCounter = 0;
    var done;

    var str = '';

    while (!done) {
        str = str + lookup( ( (number >> (4 * loopCounter)) & 0x0f ) | randomByte() );
        var comparison = Math.pow(16, loopCounter + 1);
        done = number < comparison && (!max || max < comparison);
        loopCounter++;
    }
    return str;
}
```

We should bump the version number if we decide to do this and the user should never ever change the value passed to max retrospectively! Alternatively, the latter could be avoided by including log_16(max + 1) in the id, making it one character longer though.

What do you think about this idea? If you like it, I would be willing to submit a PR.

**Comment by ai** [comment]
Yeap, this is a solution too.

But let's make on top of New stateless API. After React London (March 29) I will have more time and will enliven this project and add additional stateless API.

After it PR will be very welcome.

Is this wait time is OK for you?

**Comment by nikwen** [comment]
@ai Thank you for your reply.

I thought about this a bit more and decided that shortid wasn't the best way to build ids for my use case. So I'll leave implementing this to someone else. My comment above should be a starting point for anyone wanting to solve this problem.
