### ISSUE TITLE
Specify id length

### ISSUE THREAD

**Issue by praxiq** [dylang/shortid#81]
The automatic scaling of id length based on generation rate is pretty cool, but it has some drawbacks.

1. As one user pointed out, if ids are generated rapidly in clusters, it can create ids that are too long.
2. If run for a long time at a low rate, it can create ids that are too short! Generating 1 id per second, the ids stay short (9 characters = 54 bits). After only a year (30 million ids) the odds of a collision increase to 2.5%. (And if 4 different servers each generate 1 id per second, it'll only take 3 months to get the same odds of a collision!)

When I know my own use case and how important it is to me to avoid a collision, I'd like to be able to skip the timing code and just specify the length myself.

It'd be nice if I could call generate(12), and get output of the specified length. (Or, generateFixed could be its own function, separating out the timing code completely for those who don't want it to be part of their project.)

**Comment by flesler** [comment]
There's no odds of collision if there's a single server or you set a different worker id on each. If you have more than 16 servers, you can device a way to give each server a letter and append it to IDs and then the amount of servers you can have in the cluster safely skyrockets.

As for length, I showed [on another issue](https://github.com/dylang/shortid/issues/58#issuecomment-166401161) that they don't get that long at high-scale. As I said there, you need to generate more than 4 IDs **per millisecond** to get IDs longer than 12 chars. UUIDs take 16 bytes, 32 if you encode as strings so 12 is still a bargain.

**Comment by ai** [comment]
This library doesn’t have this API since it is dynamic ID length.

Use [Nano ID](https://github.com/ai/nanoid), where you can change ID length.
