### ISSUE TITLE
shortid is storing as objectid.

### ISSUE THREAD

**Issue by pankug** [dylang/shortid#83]
I am using shortid for my custom _id. It is generating custom _id but in the database, it is storing as objectid.Also, shortid created are  of very weird type

![short_id](https://cloud.githubusercontent.com/assets/12581773/20711683/f47ca80e-b666-11e6-8773-265330f4cc74.PNG)

![1](https://cloud.githubusercontent.com/assets/12581773/20711732/303a5184-b667-11e6-98dd-03fee2457857.PNG)

 created_at:{type: Date, default: Date.now},
    _id:{type: String, default: shortid.generate() },

**Comment by ai** [comment]
What database you use?

**Comment by Restuta** [comment]
@ai it looks like it's Mongo

**Comment by adematte** [comment]
looks like a development issue which has nothing to do with your library. I'd close it.
