### ISSUE TITLE
Uniformity?

### ISSUE THREAD

**Issue by ronzeidman** [dylang/shortid#85]
I wanted to use this as an id instead of a uuid, so I compared this library with uuid library, I've got these results after running my script for 10 minutes:
![2017-01-11 13_16_27-](https://cloud.githubusercontent.com/assets/14001863/21846531/40c3fd74-d800-11e6-844c-f53bcba0ecb5.png)

```ts
import * as shortid from 'shortid';
import * as uuidV1 from 'uuid/v1';
import * as uuidV4 from 'uuid/v4';
const canvas = <HTMLCanvasElement>document.getElementById('canvas');
const width = 1000;
const ctx = canvas.getContext('2d');
const test = (values: string, generator: () => string, y: number, name: string) => {
    ctx.fillRect((width - 2),5, 2, y);
    ctx.fillRect(0,5, 2, y);
    ctx.fillText(name, width + 1, y);
    setInterval(() => {
        const str = generator();
        let val = 0;
        for (let idx = 0; idx < str.length; idx++) {
            val += values.indexOf(str.charAt(idx)) / (values.length ** (idx + 1))
        }
        console.log(val);
        ctx.fillRect(val * (width - 1),y, 1, 1);
    }, 100);
};
test('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-', shortid.generate, 10, 'shortid');
test('abcdef0123456789-', uuidV1, 20, 'uuidV1 (time-based)');
test('abcdef0123456789-', uuidV4, 30, 'uuidV4 (random)');
```
The ids seems to not be uniformly distributed (or something is lacking in my quickly written script) so I can't use this as a good sharding key.
Is there any way of making the ids mode distributed?

**Comment by ronzeidman** [comment]
updated the code with "timekeeper" so I could test it in random times throughout the year, I've got the same result:
```ts
import * as shortid from 'shortid';
import * as uuid from 'uuid';
import * as tk from 'timekeeper';
import * as basex from 'base-x';
import {parse, unparse} from 'uuid-parse';

const canvas = <HTMLCanvasElement>document.getElementById('canvas');
const width = 1000;
const ctx = canvas.getContext('2d');
const friendlyChars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789_-';
const hex = '0123456789abcdef';
const b64 = basex(friendlyChars);

const test = (values: string, generator: () => string, y: number, name: string) => {
    ctx.fillRect((width - 2), 5, 2, y);
    ctx.fillRect(0, 5, 2, y);
    ctx.fillText(name, width + 1, y);
    for (let i = 0; i < 200; i++) {
        const str = generator();
        let val = 0;
        for (let idx = 0; idx < str.length; idx++) {
            val += values.indexOf(str.charAt(idx)) / (values.length ** (idx + 1))
        }
        ctx.fillRect(val * (width - 1), y, 1, 1);
        tk.travel(new Date(Date.now() + Math.random() * 1000 * 60 * 60 * 24 * 365))
    }
};
const randomChar = () => friendlyChars.charAt(Math.floor(Math.random() * friendlyChars.length));
const randomChars = (num: number) => {
    let str = '';
    for (let i = 0; i < num; i++) {
        str += randomChar();
    }
    return str;
};
setInterval(() => {
    ctx.clearRect(0, 0 , canvas.width, canvas.height);
    test(friendlyChars, () => randomChars(10), 10, 'random 10 chars');
    test(friendlyChars, shortid.generate, 20, 'shortid');
    test(hex + '-', uuid.v1, 30, 'uuidV1 (time-based)');
    test(hex + '-', uuid.v4, 40, 'uuidV4 (random)');
    test(friendlyChars, () => b64.encode(parse(uuid.v4())), 50, 'uuidV4 (encoded)');
}, 100);
```

![image](https://cloud.githubusercontent.com/assets/14001863/21880009/23b608f8-d8a5-11e6-8ab6-5d0d2ddeb7ee.png)

**Comment by ai** [comment]
It could be big problem. Any ideas how we can fix it?

**Comment by drostie** [comment]
This is not necessarily an issue because shortid is not *meant* to be a general RNG. Instead it is based on encoding an increasing counter; several messages (in the form of variable-length numbers) are broken into 4-bit chunks, each of which is encoded by a random choice of one of 4 16-character alphabets (chosen by shuffling the 64-character alphabet and then dividing it into those 4 alphabets). Non-uniformity in the increasing counter is therefore reflected in the output values; for example the first letter will always be only one of 4 options. However sharding is definitely a good usage case for random IDs and there are better ways to generate more-random keys that might be useful for sharding, so maybe it is a valid issue.

**Comment by ai** [comment]
I didn’t find the way how to fix it in `shortid` with existed API, so I created the new project with guaranteed uniformity:
https://github.com/ai/nanoid

**Comment by ai** [comment]
We start to use Nano ID and added uniformity test: `node test/distribution.js`.

Now it seems to be much better.
