### ISSUE TITLE
ES6 import fail

### ISSUE THREAD

**Issue by jonathanborges1542** [dylang/shortid#87]
I cant import with es6 style! PLX FIX THIS! THANKS!

**Comment by ai** [comment]
What error do you have? And do you use Babel or what node.js version?

**Comment by jonathanborges** [comment]
Babel, angular 2 project. import 'shortid' from 'shortid'.

**Comment by ai** [comment]
Try to remove quotes around variable name:

```js
 import shortid from 'shortid'
```

If you will still have issue, please show full stacktrace (always try to start any issue report with full stacktrace)

**Comment by jay-at-avido** [comment]
This seems to work for me:
import shortid from 'shortid32'

**Comment by ai** [comment]
Nobody reported an error stacktrace. Closing.

**Comment by sevaTechoPark** [comment]
what stacktrace? import as undefined when run with nodejs + typescript + cluster

**Comment by seanelias** [comment]
you need to import as below
`import * as shortid from 'shortid';`
