### ISSUE TITLE
Support upsert?

### ISSUE THREAD

**Issue by vylan** [dylang/shortid#90]
Hi,

I've defined the _id field: `_id: {
        type: String,
        'default': shortid.generate
    },`
then I performed a query like this:
`this.findOneAndUpdate(condition, {
            $set: {
                // ...
            }
        }, {
            new: true,
            upsert: true,
        }, cb)`
It still inserted a document with an ObjectId _id. Am I wrong or does it not support upsert operation?

**Comment by ai** [comment]
@vylan honestly, it will be better to ask in Mongoose community and then send PR with docs fix.

Origin maintainer (@dylang) have no time right now. I don’t have any experience with Mongoose.

**Comment by BlakeBrown** [comment]
@vylan it's a really bad idea to use a library like this for unique database ID's. You want to guarantee the uniqueness of your Mongo documents, so you should stick with the auto generated ObjectId's that mongo provides. This way you will not run into collisions (duplicate ID's) when querying documents.
