### ISSUE TITLE
Java port review

### ISSUE THREAD

**Issue by snimavat** [dylang/shortid#91]
Thanks for this amazing short id generator.

I have done a java port here https://github.com/snimavat/shortid

If any one want to review and has any comments/suggestions/issues

Thanks

**Comment by ai** [comment]
Nice :). If you are making a port, I recommend you to fix few `shortid` issues:

1. Do not use state API. Change API to be stateless. https://github.com/dylang/shortid/issues/48
2. Test and fix random distribution problem https://github.com/dylang/shortid/issues/85 Maybe replacing a RNG will be a good idea https://github.com/dylang/shortid/issues/70

**Comment by snimavat** [comment]
Okay, will look into that
